{
 "title": "Locust Prometheus",
 "tags": [
  "Locust",
  "Prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "RPS Total",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 21, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(locust_requests_total[1m]))",
     "legendFormat": "RPS Total"
    },
    {
     "expr": "sum(rate(locust_requests_total{status=~\"4..|5..|0\"}[1m]))",
     "legendFormat": "RPS KO"
    },
    {
     "expr": "sum(rate(locust_requests_total{status!~\"4..|5..|0\"}[1m]))",
     "legendFormat": "RPS OK"
    }
   ]
  },
  {
   "title": "Successful %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(locust_requests_total{status!~\"4..|5..|0\"}[5m])) / sum(rate(locust_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error %",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(locust_requests_total{status=~\"4..|5..|0\"}[5m])) / sum(rate(locust_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPS OK",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(locust_requests_total{status!~\"4..|5..|0\"}[1m])",
       "legendFormat": "{{method}} {{endpoint}}"
      }
     ]
    },
    {
     "title": "RPS KO",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(locust_requests_total{status=~\"4..|5..|0\"}[1m])",
       "legendFormat": "{{method}} {{endpoint}}"
      }
     ]
    }
   ]
  },
  {
   "title": "latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "99%",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(locust_request_duration_seconds_bucket[1m])) by (le, endpoint))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "95%",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(locust_request_duration_seconds_bucket[1m])) by (le, endpoint))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "75%",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.75, sum(rate(locust_request_duration_seconds_bucket[1m])) by (le, endpoint))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "50%",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(locust_request_duration_seconds_bucket[1m])) by (le, endpoint))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}