{
 "title": "Locust InfluxDB2",
 "tags": [
  "Locust",
  "infuxdb2"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "influxdb" }
  ]
 },
 "panels": [
  {
   "title": "RPS Total",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 16, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n      r[\"_measurement\"] == \"locust_requests\" and\n      r[\"_field\"] == \"status_code\" and\n      r.name =~ /^ur/\n  )\n  |> group(columns: [\"name\"])\n  |> aggregateWindow(every: 30s, fn: count, createEmpty: false)\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) / 30.0 }))\n  |> yield(name: \"rps_30s\")"
    }
   ]
  },
  {
   "title": "RPS Total OK",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n      r[\"_measurement\"] == \"locust_requests\" and\n      r[\"_field\"] == \"status_code\" and\n      r.name =~ /^ur/ and\n      r._value < 400\n  )\n  |> group(columns: [\"name\"])\n  |> aggregateWindow(every: 30s, fn: count, createEmpty: false)\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) / 30.0 }))\n  |> yield(name: \"rps_30s\")"
    }
   ]
  },
  {
   "title": "Successful %",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"locust_requests\" and\n    r._field == \"status_code\" and\n    r.name =~ /^ur/\n  )\n  |> group()\n  |> reduce(\n    identity: {all: 0, success: 0},\n    fn: (r, accumulator) => ({\n      all: accumulator.all + 1,\n      success: accumulator.success + (if r._value < 400 then 1 else 0)\n    })\n  )\n  |> map(fn: (r) => ({\n    _time: now(),\n    _measurement: \"locust_requests\",\n    _field: \"success_rate\",\n    _value: if r.all == 0 then 0.0 else float(v: r.success) / float(v: r.all)\n  }))"
    }
   ]
  },
  {
   "title": "RPS Total KO",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n      r[\"_measurement\"] == \"locust_requests\" and\n      r[\"_field\"] == \"status_code\" and\n      r.name =~ /^ur/ and\n      r._value >= 400\n  )\n  |> group(columns: [\"name\"])\n  |> aggregateWindow(every: 30s, fn: count, createEmpty: false)\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) / 30.0 }))\n  |> yield(name: \"rps_30s\")"
    }
   ]
  },
  {
   "title": "Error %",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"locust_requests\" and\n    r._field == \"status_code\" and\n    r.name =~ /^ur/\n  )\n  |> group()\n  |> reduce(\n    identity: {all: 0, success: 0},\n    fn: (r, accumulator) => ({\n      all: accumulator.all + 1,\n      success: accumulator.success + (if r._value >= 400 then 1 else 0)\n    })\n  )\n  |> map(fn: (r) => ({\n    _time: now(),\n    _measurement: \"locust_requests\",\n    _field: \"success_rate\",\n    _value: if r.all == 0 then 0.0 else float(v: r.success) / float(v: r.all)\n  }))"
    }
   ]
  },
  {
   "title": "Summary UC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Summary UC",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
     "targets": [
      {
       "query": "from(bucket: \"metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"locust_requests\" and\n    r._field == \"status_code\" and\n    r.name =~ /^uc/\n  )\n  |> group(columns: [\"name\"])\n  |> reduce(\n    identity: {all: 0, err: 0},\n    fn: (r, accumulator) => ({\n      all: accumulator.all + 1,\n      err: accumulator.err + (if r._value >= 400 then 1 else 0)\n    })\n  )\n  |> map(fn: (r) => ({\n    transaction: r.name,\n    success_count: r.all - r.err,\n    error_count: r.err,\n    error_percent: if r.all == 0 then 0.0 else float(v: r.err) / float(v: r.all)\n  }))\n  |> keep(columns: [\"transaction\", \"success_count\", \"error_count\", \"error_percent\"])\n  |> yield(name: \"requests_summary\")"
      }
     ]
    }
   ]
  },
  {
   "title": "UC TPS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "TPS OK",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "query": "from(bucket: \"metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n      r[\"_measurement\"] == \"locust_requests\" and\n      r[\"_field\"] == \"status_code\" and\n      r.name =~ /^uc/ and\n      r._value < 400\n  )\n  |> group(columns: [\"name\"])\n  |> aggregateWindow(every: 30s, fn: count, createEmpty: false)\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) / 30.0 }))\n  |> yield(name: \"rps_30s\")"
      }
     ]
    },
    {
     "title": "TPS KO",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "query": "from(bucket: \"metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n      r[\"_measurement\"] == \"locust_requests\" and\n      r[\"_field\"] == \"status_code\" and\n      r.name =~ /^uc/ and\n      r._value >= 400\n  )\n  |> group(columns: [\"name\"])\n  |> aggregateWindow(every: 30s, fn: count, createEmpty: false)\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) / 30.0 }))\n  |> yield(name: \"rps_30s\")"
      }
     ]
    }
   ]
  },
  {
   "title": "UC Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "99%",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "query": "from(bucket: \"metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"locust_requests\" and r[\"_field\"] == \"response_time_ms\" and r.name =~ /^uc/)\n  |> group(columns: [\"name\"])\n  |> aggregateWindow(\n      every: 30s,\n      fn: (tables=<-, column) => tables |> quantile(q: 0.99, method: \"estimate_tdigest\"),\n      createEmpty: false\n  )\n  |> yield(name: \"p99_30s\")"
      }
     ]
    },
    {
     "title": "95%",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "query": "from(bucket: \"metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"locust_requests\" and r[\"_field\"] == \"response_time_ms\" and r.name =~ /^uc/)\n  |> group(columns: [\"name\"])\n  |> aggregateWindow(\n      every: 30s,\n      fn: (tables=<-, column) => tables |> quantile(q: 0.95, method: \"estimate_tdigest\"),\n      createEmpty: false\n  )\n  |> yield(name: \"p95_30s\")"
      }
     ]
    },
    {
     "title": "75%",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "query": "from(bucket: \"metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"locust_requests\" and r[\"_field\"] == \"response_time_ms\" and r.name =~ /^uc/)\n  |> group(columns: [\"name\"])\n  |> aggregateWindow(\n      every: 30s,\n      fn: (tables=<-, column) => tables |> quantile(q: 0.75, method: \"estimate_tdigest\"),\n      createEmpty: false\n  )\n  |> yield(name: \"p75_30s\")"
      }
     ]
    },
    {
     "title": "50%",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "query": "from(bucket: \"metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"locust_requests\" and r[\"_field\"] == \"response_time_ms\" and r.name =~ /^uc/)\n  |> group(columns: [\"name\"])\n  |> aggregateWindow(\n      every: 30s,\n      fn: (tables=<-, column) => tables |> quantile(q: 0.50, method: \"estimate_tdigest\"),\n      createEmpty: false\n  )\n  |> yield(name: \"p50_30s\")"
      }
     ]
    }
   ]
  },
  {
   "title": "Summary UR",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Summary UR",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 120 },
     "targets": [
      {
       "query": "from(bucket: \"metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"locust_requests\" and\n    r._field == \"status_code\" and\n    r.name =~ /^ur/\n  )\n  |> group(columns: [\"name\"])\n  |> reduce(\n    identity: {all: 0, err: 0},\n    fn: (r, accumulator) => ({\n      all: accumulator.all + 1,\n      err: accumulator.err + (if r._value >= 400 then 1 else 0)\n    })\n  )\n  |> map(fn: (r) => ({\n    transaction: r.name,\n    success_count: r.all - r.err,\n    error_count: r.err,\n    error_percent: if r.all == 0 then 0.0 else float(v: r.err) / float(v: r.all)\n  }))\n  |> keep(columns: [\"transaction\", \"success_count\", \"error_count\", \"error_percent\"])\n  |> yield(name: \"requests_summary\")"
      }
     ]
    }
   ]
  },
  {
   "title": "UR RPS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPS OK",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 302 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "query": "from(bucket: \"metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n      r[\"_measurement\"] == \"locust_requests\" and\n      r[\"_field\"] == \"status_code\" and\n      r.name =~ /^ur/ and\n      r._value < 400\n  )\n  |> group(columns: [\"name\"])\n  |> aggregateWindow(every: 30s, fn: count, createEmpty: false)\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) / 30.0 }))\n  |> yield(name: \"rps_30s\")"
      }
     ]
    },
    {
     "title": "RPS KO",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 302 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "query": "from(bucket: \"metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n      r[\"_measurement\"] == \"locust_requests\" and\n      r[\"_field\"] == \"status_code\" and\n      r.name =~ /^ur/ and\n      r._value >= 400\n  )\n  |> group(columns: [\"name\"])\n  |> aggregateWindow(every: 30s, fn: count, createEmpty: false)\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) / 30.0 }))\n  |> yield(name: \"rps_30s\")"
      }
     ]
    }
   ]
  },
  {
   "title": "UR Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "99%",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "query": "from(bucket: \"metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"locust_requests\" and r[\"_field\"] == \"response_time_ms\" and r.name =~ /^ur/)\n  |> group(columns: [\"name\"])\n  |> aggregateWindow(\n      every: 30s,\n      fn: (tables=<-, column) => tables |> quantile(q: 0.99, method: \"estimate_tdigest\"),\n      createEmpty: false\n  )\n  |> yield(name: \"p99_30s\")"
      }
     ]
    },
    {
     "title": "95%",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "query": "from(bucket: \"metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"locust_requests\" and r[\"_field\"] == \"response_time_ms\" and r.name =~ /^ur/)\n  |> group(columns: [\"name\"])\n  |> aggregateWindow(\n      every: 30s,\n      fn: (tables=<-, column) => tables |> quantile(q: 0.95, method: \"estimate_tdigest\"),\n      createEmpty: false\n  )\n  |> yield(name: \"p95_30s\")"
      }
     ]
    },
    {
     "title": "75%",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "query": "from(bucket: \"metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"locust_requests\" and r[\"_field\"] == \"response_time_ms\" and r.name =~ /^ur/)\n  |> group(columns: [\"name\"])\n  |> aggregateWindow(\n      every: 30s,\n      fn: (tables=<-, column) => tables |> quantile(q: 0.75, method: \"estimate_tdigest\"),\n      createEmpty: false\n  )\n  |> yield(name: \"p75_30s\")"
      }
     ]
    },
    {
     "title": "50%",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "query": "from(bucket: \"metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"locust_requests\" and r[\"_field\"] == \"response_time_ms\" and r.name =~ /^ur/)\n  |> group(columns: [\"name\"])\n  |> aggregateWindow(\n      every: 30s,\n      fn: (tables=<-, column) => tables |> quantile(q: 0.50, method: \"estimate_tdigest\"),\n      createEmpty: false\n  )\n  |> yield(name: \"p50_30s\")"
      }
     ]
    }
   ]
  }
 ]
}